services:
  postgres:
    image: postgres:15
    container_name: generic-login-postgres
    env_file:
      - ./Api/.env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
